version: "3.8"

services: 
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app_db
    volumes:
      - "./script.sql:/docker-entrypoint-initdb.d/1.sql"
  app:
    build: .
    ports:
      - "8080:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app_db
      MYSQL_URL: mysql://app:app@mysql:3306/app_db
